modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"

[[mixins]]
config = "puffish_attributes.mixins.json"

[[mods]]
modId="puffish_attributes"
version="${version}"
displayName="Pufferfish's Attributes"
authors="Pufferfish"
description="Adds more attributes to the game."

[[dependencies.puffish_attributes]]
modId="neoforge"
type="required"
versionRange="[21.0.0-beta,)"

[[dependencies.puffish_attributes]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1)"

[[dependencies.puffish_attributes]]
modId="puffish_skills"
type="incompatible"
versionRange="(,0.12.0)"
